name: Observability Stack 

on:
 workflow_dispatch:

jobs:
  observability_stack:
    uses: veecode-platform/vkpr_templates/.github/workflows/observability.yml@1.3.5
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}


